// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type RunAgentRunPostData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Goal
         */
        goal: string;
    };
    url: '/run';
};

export type RunAgentRunPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RunAgentRunPostError = RunAgentRunPostErrors[keyof RunAgentRunPostErrors];

export type RunAgentRunPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
